//disposable
export const ADD_EDITING_ROLE = 'ADD_EDITING_ROLE';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const ADD_VALIDATION = 'ADD_VALIDATION';
export const CLEAR_DISPOSABLE = 'CLEAR_DISPOSABLE';

//request user infomation
export const REQUEST_USERINFO = 'REQUEST_USERINFO';
export const REQUEST_USERINFO_SUCCESS = 'REQUEST_USERINFO_SUCCESS';
export const REQUEST_USERINFO_FAIL = 'REQUEST_USERINFO_FAIL';

export const UPDATE_USERINFO_TICKETS = 'UPDATE_USERINFO_TICKETS';
export const UPDATE_USERINFO_RESERVATION = 'UPDATE_USERINFO_RESERVATION';

export const CHANGE_PASS = 'CHANGE_PASS';
export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS';
export const CHANGE_PASS_FAIL = 'CHANGE_PASS_FAIL';

//message
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const ADD_SIDE_ALERT = 'ADD_SIDE_ALERT';
export const DELETE_SIDE_ALERT = 'DELETE_SIDE_ALERT';

//timetable
export const SET_TYPE_STATUS = 'SET_TYPE_STATUS';
export const CHANGE_TYPE_CHECKED = 'CHANGE_TYPE_CHECKED';

export const SET_PLACE_STATUS = 'SET_PLACE_STATUS';
export const CHANGE_PLACE_ACTIVE = 'CHANGE_PLACE_ACTIVE';
export const CHANGE_PLACE_CHECKED = 'CHANGE_PLACE_CHECKED';

export const CHANGE_WEEK = 'CHANGE_WEEK';

export const REQUEST_TIMETABLE = 'REQUEST_TIMETABLE';
export const REQUEST_TIMETABLE_SUCCESS = 'REQUEST_TIMETABLE_SUCCESS';
export const REQUEST_TIMETABLE_FAIL = 'REQUEST_TIMETABLE_FAIL';
export const TIMETABLE_IS_OLD = 'TIMETABLE_IS_OLD';
export const SET_PLANS = 'SET_PLANS';

export const MODAL_ON = 'MODAL_ON';
export const MODAL_OFF = 'MODAL_OFF';

//reservations
export const REQUEST_RESERVATIONS = 'REQUEST_RESERVATIONS';
export const REQUEST_RESERVATIONS_SUCCESS = 'REQUEST_RESERVATIONS_SUCCESS';
export const REQUEST_RESERVATIONS_FAIL = 'REQUEST_RESERVATIONS_FAIL';
export const DO_CANCEL_ACTION = 'DO_CANCEL_ACTION';
export const DONE_CANCEL_ACTION = 'DONE_CANCEL_ACTION';

//ticket
export const CHANGE_TICKET_PANEL = 'CHANGE_TICKET_PANEL';

export const REQUEST_TICKET = 'REQUEST_TICKET';
export const REQUEST_TICKET_SUCCESS = 'REQUEST_TICKET_SUCCESS';
export const REQUEST_TICKET_FAIL = 'REQUEST_TICKET_FAIL';

//log
export const REQUEST_LOG = 'REQUEST_LOG';
export const REQUEST_LOG_SUCCESS = 'REQUEST_LOG_SUCCESS';
export const REQUEST_LOG_FAIL = 'REQUEST_LOG_FAIL';
export const SET_LOG_PAGE = 'SET_LOG_PAGE';
export const CLEAR_LOG = 'CLEAR_LOG';

//jwt token
export const SET_TEST_TOKEN = 'SET_TEST_TOKEN';
export const DELETE_TEST_TOKEN = 'DELETE_TEST_TOKEN';
export const SET_CONF_TOKEN = 'SET_CONF_TOKEN';
export const DELETE_CONF_TOKEN = 'DELETE_CONF_TOKEN';
