<?php

use Carbon\Carbon as Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Class UserTableSeeder
 */
class UserTableSeeder extends Seeder
{
    public function run()
    {
        if (env('DB_CONNECTION') == 'mysql') {
            DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        }

        if (env('DB_CONNECTION') == 'mysql') {
            DB::table(config('access.users_table'))->truncate();
        } elseif (env('DB_CONNECTION') == 'sqlite') {
            DB::statement('DELETE FROM ' . config('access.users_table'));
        } else {
            //For PostgreSQL or anything else
            DB::statement('TRUNCATE TABLE ' . config('access.users_table') . ' CASCADE');
        }

        //Add the master administrator, user id of 1
        $users = [
            [
                'user_id'           => 'Admin Istrator',
                'name'              => 'Admin Istrator',
                'first_name'        => 'Admin',
                'last_name'         => 'Istrator',
                'email'             => 'admin@admin.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'View Backend',
                'name'              => 'View Backend',
                'first_name'        => 'View',
                'last_name'         => 'Backend',
                'email'             => 'view-backend@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'View Access Management',
                'name'              => 'View Access Management',
                'first_name'        => 'View',
                'last_name'         => 'AccessManagement',
                'email'             => 'view-access-management@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'Edit Users',
                'name'              => 'Edit Users',
                'first_name'        => 'Edit',
                'last_name'         => 'Users',
                'email'             => 'edit@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'Except Permanently Delete Users',
                'name'              => 'Except Permanently Delete Users',
                'first_name'        => 'Except',
                'last_name'         => 'Permanently Delete Users',
                'email'             => 'except@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'Default User',
                'name'              => 'Default User',
                'first_name'        => 'Default',
                'last_name'         => 'User',
                'email'             => 'user@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'Default User2',
                'name'              => 'Default User2',
                'first_name'        => 'Default',
                'last_name'         => 'User2',
                'email'             => 'user2@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'Default User3',
                'name'              => 'Default User3',
                'first_name'        => 'Default',
                'last_name'         => 'User3',
                'email'             => 'user3@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'Default User4',
                'name'              => 'Default User4',
                'first_name'        => 'Default',
                'last_name'         => 'User4',
                'email'             => 'user4@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'Default User5',
                'name'              => 'Default User5',
                'first_name'        => 'Default',
                'last_name'         => 'User5',
                'email'             => 'user5@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'Default User6',
                'name'              => 'Default User6',
                'first_name'        => 'Default',
                'last_name'         => 'User5',
                'email'             => 'user6@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'Default User7',
                'name'              => 'Default User7',
                'first_name'        => 'Default',
                'last_name'         => 'User5',
                'email'             => 'user7@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',                
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'Default User8',
                'name'              => 'Default User8',
                'first_name'        => 'Default',
                'last_name'         => 'User5',
                'email'             => 'user8@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',                
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'Default User9',
                'name'              => 'Default User9',
                'first_name'        => 'Default',
                'last_name'         => 'User5',
                'email'             => 'user9@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',                
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'Default User10',
                'name'              => 'Default User10',
                'first_name'        => 'Default',
                'last_name'         => 'User5',
                'email'             => 'user10@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',                
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'Default User11',
                'name'              => 'Default User11',
                'first_name'        => 'Default',
                'last_name'         => 'User5',
                'email'             => 'user11@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',                
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'Default User12',
                'name'              => 'Default User12',
                'first_name'        => 'Default',
                'last_name'         => 'User5',
                'email'             => 'user12@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',                
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'Default User13',
                'name'              => 'Default User13',
                'first_name'        => 'Default',
                'last_name'         => 'User5',
                'email'             => 'user13@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',                
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'Default User14',
                'name'              => 'Default User14',
                'first_name'        => 'Default',
                'last_name'         => 'User5',
                'email'             => 'user14@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',                
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'Default User15',
                'name'              => 'Default User15',
                'first_name'        => 'Default',
                'last_name'         => 'User5',
                'email'             => 'user15@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',                
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'Default User16',
                'name'              => 'Default User16',
                'first_name'        => 'Default',
                'last_name'         => 'User5',
                'email'             => 'user16@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',                
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'Default User17',
                'name'              => 'Default User17',
                'first_name'        => 'Default',
                'last_name'         => 'User5',
                'email'             => 'user17@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',                
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'Default User18',
                'name'              => 'Default User18',
                'first_name'        => 'Default',
                'last_name'         => 'User5',
                'email'             => 'user18@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',                
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'Default User19',
                'name'              => 'Default User19',
                'first_name'        => 'Default',
                'last_name'         => 'User5',
                'email'             => 'user19@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',                
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'user_id'           => 'Default User20',
                'name'              => 'Default User20',
                'first_name'        => 'Default',
                'last_name'         => 'User5',
                'email'             => 'user20@user.com',
                'age'               => '25',
                'sex'               => '0',
                'postal_code'       => '1000014',
                'state'             => '東京都',
                'city'              => '千代田区',
                'street'            => '永田町１丁目７−１',
                'building'          => '',                
                'password'          => bcrypt('123456'),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ]
        ];

        DB::table(config('access.users_table'))->insert($users);

        if (env('DB_CONNECTION') == 'mysql') {
            DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        }
    }
}