export const ADD_EDITING_ROLE = 'ADD_EDITING_ROLE';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const ADD_VALIDATION = 'ADD_VALIDATION';

//request user infomation
export const REQUEST_USERINFO = 'REQUEST_USERINFO';
export const REQUEST_USERINFO_SUCCESS = 'REQUEST_USERINFO_SUCCESS';
export const REQUEST_USERINFO_FAIL = 'REQUEST_USERINFO_FAIL';

export const UPDATE_USERINFO_TICKETS = 'UPDATE_USERINFO_TICKETS';
export const UPDATE_USERINFO_RESERVATION = 'UPDATE_USERINFO_RESERVATION';

export const CHANGE_PASS = 'CHANGE_PASS';
export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS';
export const CHANGE_PASS_FAIL = 'CHANGE_PASS_FAIL';

//message
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const ADD_SIDE_ALERT = 'ADD_SIDE_ALERT';
export const DELETE_SIDE_ALERT = 'DELETE_SIDE_ALERT';

//reservations
export const REQUEST_RESERVATIONS = 'REQUEST_RESERVATIONS';
export const REQUEST_RESERVATIONS_SUCCESS = 'REQUEST_RESERVATIONS_SUCCESS';
export const REQUEST_RESERVATIONS_FAIL = 'REQUEST_RESERVATIONS_FAIL';

export const CANCEL = 'CANCEL';
export const CANCEL_SUCCESS = 'CANCEL_SUCCESS';
export const CANCEL_FAIL = 'CANCEL_FAIL';

//ticket
export const CHANGE_TICKET_PANEL = 'CHANGE_TICKET_PANEL';

export const REQUEST_TICKET = 'REQUEST_TICKET';
export const REQUEST_TICKET_SUCCESS = 'REQUEST_TICKET_SUCCESS';
export const REQUEST_TICKET_FAIL = 'REQUEST_TICKET_FAIL';

//log
export const REQUEST_TICKET_LOG = 'REQUEST_TICKET_LOG';
export const REQUEST_TICKET_LOG_SUCCESS = 'REQUEST_TICKET_LOG_SUCCESS';
export const REQUEST_TICKET_LOG_FAIL = 'REQUEST_TICKET_LOG_FAIL';

export const REQUEST_RESERVATION_LOG = 'REQUEST_RESERVATION_LOG';
export const REQUEST_RESERVATION_LOG_SUCCESS = 'REQUEST_RESERVATION_LOG_SUCCESS';
export const REQUEST_RESERVATION_LOG_FAIL = 'REQUEST_RESERVATION_LOG_FAIL';
