export const REQUEST_TIMETABLE = 'REQUEST_TIMETABLE';
export const REQUEST_TIMETABLE_SUCCESS = 'REQUEST_TIMETABLE_SUCCESS';
export const REQUEST_TIMETABLE_FAIL = 'REQUEST_TIMETABLE_FAIL';

export const CONFIRM_RESERVATION = 'CONFIRM_RESERVATION';
export const CONFIRM_RESERVATION_SUCCESS = 'CONFIRM_RESERVATION_SUCCESS';
export const CONFIRM_RESERVATION_FAIL = 'CONFIRM_RESERVATION_FAIL';

export const CONNECTION_TEST = 'CONNECTION_TEST';
export const CONNECTION_TEST_SUCCESS = 'CONNECTION_TEST_SUCCESS';
export const CONNECTION_TEST_FAIL = 'CONNECTION_TEST_FAIL';

export const RESERVE = 'RESERVE';
export const RESERVE_SUCCESS = 'RESERVE_SUCCESS';
export const RESERVE_FAIL = 'RESERVE_FAIL';

export const UPDATE_USERINFO_RESERVATION = 'UPDATE_USERINFO_RESERVATION';
